TODO

- handle username, password if not setted in .git/config
- pc6248 dell switch: half work is done, runnin config is ok, with web ui
- why pc6248 doesnt work with ssh paramiko, broken channel?
- better dokumentation
- better error handling
- test access rights for file or dirs


[+] copy myIP@myRemotePath  to myLocalPath
Traceback (most recent call last):
  File "smc.py", line 153, in <module>
    get_copy_remote(host)
  File "smc.py", line 71, in get_copy_remote
    ftp.get(remotepath, repo+"/"+localpath)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 673, in get
    file_size = self.stat(remotepath).st_size
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 337, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 689, in _request
    return self._read_response(num)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 736, in _read_response
    self._convert_status(msg)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 762, in _convert_status
    raise IOError(errno.ENOENT, text)
IOError: [Errno 2] No such file

after second start it work, WTF is happening?
